create table ticket(
    ID int PRIMARY KEY AUTO_INCREMENT,
    PARKING_NUMBER int NOT NULL,
    VEHICLE_REG_NUMBER varchar(10) NOT NULL,
    PRICE double,
    IN_TIME DATETIME NOT NULL,
    OUT_TIME DATETIME,
    FOREIGN KEY (PARKING_NUMBER) REFERENCES parking(PARKING_NUMBER)
);
